services:
  frontend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/todo-app/client:latest
    ports:
      - "80:80"
    environment:
      - BACKEND_HOST=${EC2_HOST:-localhost}
      - BACKEND_PORT=3001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - todo-network

  backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/todo-app/server:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - AWS_REGION=eu-west-1
      - DYNAMODB_TABLE_NAME=todo-app-todos
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
