services:
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        ports:
            - "80:80"
        environment:
            - REACT_APP_API_URL=http://3.251.78.158:5001
        depends_on:
            - server
        restart: unless-stopped
        networks:
            - todo-network
        logging:
            driver: awslogs
            options:
                awslogs-group: /aws/todo-app/client
                awslogs-region: eu-west-1
                awslogs-stream-prefix: client
                awslogs-create-group: "true"

    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports:
            - "5001:5001"
        environment:
            - NODE_ENV=production
            - PORT=5001
            - AWS_REGION=eu-west-1
            - DYNAMODB_TABLE_NAME=todo-app-todos
        restart: unless-stopped
        networks:
            - todo-network
        logging:
            driver: awslogs
            options:
                awslogs-group: /aws/todo-app/server
                awslogs-region: eu-west-1
                awslogs-stream-prefix: server
                awslogs-create-group: "true"

    cloudwatch-agent:
        image: amazon/cloudwatch-agent:latest
        volumes:
            - /proc:/rootfs/proc:ro
            - /sys:/rootfs/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /cgroup:/rootfs/cgroup:ro
            - ./cloudwatch-config.json:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json:ro
        environment:
            - CW_CONFIG_CONTENT=file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
        restart: unless-stopped
        networks:
            - todo-network
        logging:
            driver: awslogs
            options:
                awslogs-group: /aws/todo-app/system
                awslogs-region: eu-west-1
                awslogs-stream-prefix: cloudwatch-agent
                awslogs-create-group: "true"

networks:
    todo-network:
        driver: bridge
