FROM node:18-alpine

RUN apk add --no-cache git curl

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install -g nodemon

EXPOSE 5001

ENV NODE_ENV=development
ENV PORT=5001

CMD ["nodemon", "src/index.js"]